//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2G3_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;

    public partial class CUSTOMER_ORDER_VIEW
    {
        public IEnumerable<CUSTOMER_ORDER> CUSTOMER_ORDER_LIST { get; set; }

        public decimal Total_Amount;
        public string Customer_ID;
        public string Order_ID;
        public string Customer_Name;
        public string Customer_Address;
        public string Current_Date;

    }
}
