//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2G3_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOES_BUSINESS_IN
    {
        public string Customer_ID { get; set; }
        public string Territory_ID { get; set; }
        public System.DateTime Business_Start_Date { get; set; }
        public Nullable<System.DateTime> Business_End_Date { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual TERRITORY TERRITORY { get; set; }
    }
}
