//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2G3_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAS_SKILL
    {
        public string Employee_ID { get; set; }
        public string Skill_ID { get; set; }
        public string Enable_Flag { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual SKILL SKILL { get; set; }
    }
}
