//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2G3_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALESPERSON
    {
        public string Salesperson_ID { get; set; }
        public string Salesperson_Name { get; set; }
        public decimal Salesperson_Telephone { get; set; }
        public Nullable<decimal> Salesperson_Fax { get; set; }
        public string Territory_ID { get; set; }
    
        public virtual TERRITORY TERRITORY { get; set; }
    }
}
